CREATE TABLE LOCATION(
	Loc_ID INT NOT NULL AUTO_INCREMENT, 
	Bldg_Code VARCHAR(4) NOT NULL, 
	Room VARCHAR(4) NOT NULL, 
	Capacity INT NOT NULL,
	PRIMARY KEY (Loc_Id)
);

CREATE TABLE TERM(
	Term_ID INT NOT NULL AUTO_INCREMENT, 
	Term_Desc VARCHAR(15) NOT NULL, 
	Status VARCHAR(15) NOT NULL, 
	Start_Date VARCHAR(10) NOT NULL,
	PRIMARY KEY (Term_ID)
);

CREATE TABLE FACULTY(
	F_ID INT NOT NULL AUTO_INCREMENT,
	F_Last VARCHAR(15) NOT NULL,
	F_First VARCHAR(15) NOT NULL,
	F_Mi VARCHAR(1),
	Loc_ID INT NOT NULL,
	F_Phone VARCHAR(11) NOT NULL,
	F_Rank VARCHAR(15) NOT NULL,
	F_Super INT,
	F_Pin VARCHAR(4) NOT NULL,
	PRIMARY KEY (F_ID),
	FOREIGN KEY (Loc_ID) REFERENCES LOCATION (Loc_ID),
	FOREIGN KEY (F_Super) REFERENCES FACULTY (F_ID)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE STUDENT(
	S_ID INT NOT NULL AUTO_INCREMENT,
	S_Last VARCHAR(15) NOT NULL,
	S_First VARCHAR(15) NOT NULL,
	S_Mi VARCHAR(1),
	S_Address VARCHAR(15) NOT NULL,
	S_City VARCHAR(15) NOT NULL,
	S_State VARCHAR(2) NOT NULL,
	S_Zip VARCHAR(5) NOT NULL,
	S_Phone VARCHAR(11),
	S_DOB DATE NOT NULL,
	S_Pin VARCHAR(4) NOT NULL,
	F_ID INT,
	Date_Enrolled DATE NOT NULL,
	PRIMARY KEY (S_ID),
	FOREIGN KEY (F_ID) REFERENCES faculty(F_ID)
		ON DELETE SET NULL
		ON UPDATE CASCADE
);

CREATE TABLE COURSE(
	Course_ID INT NOT NULL AUTO_INCREMENT,
	Course_No VARCHAR(15) NOT NULL,
	Course_name VARCHAR(30) NOT NULL,
	Credits INT NOT NULL,
	PRIMARY KEY (Course_ID),
	CHECK (Credits > 0)
);

CREATE TABLE COURSE_SECTION(
	C_Sec_ID INT NOT NULL AUTO_INCREMENT,
	Course_ID INT,
	Term_ID INT,
	Sec_Num INT NOT NULL,
	F_ID INT, 
	C_Sec_Day VARCHAR(5), 
	C_Sec_Start VARCHAR(8) NOT NULL,
	C_Sec_End VARCHAR(8) NOT NULL, 
	Loc_ID INT, 
	Max_Enrl INT NOT NULL,
	PRIMARY KEY (C_Sec_ID),
	FOREIGN KEY (Course_ID) REFERENCES COURSE (Course_ID)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY (Term_ID) REFERENCES TERM (Term_ID)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY (F_ID) REFERENCES FACULTY (F_ID)
		ON DELETE SET NULL
		ON UPDATE CASCADE,
	FOREIGN KEY (Loc_ID) REFERENCES LOCATION (Loc_ID)
		ON DELETE SET NULL 
		ON UPDATE CASCADE
);

CREATE TABLE ENROLLMENT(
	S_ID INT NOT NULL AUTO_INCREMENT, 
	C_Sec_ID INT NOT NULL, 
	Grade VARCHAR(2),
	PRIMARY KEY (S_ID),
	FOREIGN KEY (C_Sec_ID) REFERENCES COURSE_SECTION (C_Sec_ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

LOAD DATA INFILE 'C:\location.txt' INTO TABLE LOCATION FIELDS TERMINATED BY ',';
LOAD DATA INFILE 'C:\erm.txt' INTO TABLE TERM FIELDS TERMINATED BY ',';
LOAD DATA INFILE 'C:\faculty.txt' INTO TABLE TERM FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n';
SELECT * FROM TERM;
